server:
  port: 0

spring:
  profiles:
    include:
      - datasource
      - token
  jpa:
    properties:
      format_sql: true
      show_sql: true
      jdbc.lob.non_contextual_creation: true
    generate-ddl: true
  application:
    name: user-service
#    hibernate:
#      ddl-auto: validate
#logging:
#  level:
#    root: debug

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka